name: iot-ml
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.2.2
  - numpy=1.26.4
  - dask
  - tqdm=4.66.5
  - joblib=1.4.2
  - scikit-learn=1.5.2
  - imbalanced-learn=0.12.3
  - xgboost=2.1.1
  - tensorflow=2.17.0
  - statsmodels
  - scipy
  - matplotlib
  - seaborn
  - pip
  - pip:
      - dask[dataframe]
